[package]
name = "rust_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25"

[[bin]]
name = "rust_shell"
path = "main.rs"
